# 快速开始序贯（Sequential）模型

### 通过向Sequential模型传递一个layer的list来构造该模型

In [1]:
from keras.models import Sequential
from keras.layers import Dense, Activation

model = Sequential([
Dense(32, units=784),
Activation('relu'),
Dense(10),
Activation('softmax'),
])

Using TensorFlow backend.


TypeError: __init__() got multiple values for argument 'units'

In [2]:
from keras.models import Sequential
from keras.layers import Dense, Activation

model = Sequential([
Dense(32, input_dim=784),   # 第二个参数应该是 输入的维度，第一个参数才是 单元数
Activation('relu'),
Dense(10),
Activation('softmax'),
])

### 通过.add()方法一个个的将layer加入模型中

In [3]:
model = Sequential()
model.add(Dense(32, input_shape=(784,)))
model.add(Activation('relu'))

## 指定输入数据的shape

Sequential的第一层需要接受一个关于输入数据shape的参数

input_shape是一个tuple类型的数据

2D层Dense，支持通过指定其输入维度input_dim来隐含的指定输入数据shape。

3D时域层支持通过参数input_dim和input_length来指定输入shape。

例如你想指定输入张量的batch大小是32，数据shape是（6，8），则你需要传递batch_size=32和input_shape=(6,8)。

In [5]:
model = Sequential()
model.add(Dense(32, input_dim=784))

In [9]:
model = Sequential()
model.add(Dense(32, input_shape=(784,)))

## 编译

三个参数：

优化器optimizer,  如rmsprop、adagrad

损失函数loss,  为模型试图最小化的目标函数,  如categorical_crossentropy、mse

指标列表metrics,  对分类问题，一般将该列表设置为metrics=['accuracy']

In [10]:
# For a multi-class classification problem
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [11]:
# For a binary classification problem
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [12]:
# For a mean squared error regression problem
model.compile(optimizer='rmsprop',
              loss='mse')

In [13]:
# 自定义 metrics
import keras.backend as K

def mean_pred(y_true, y_pred):
    return K.mean(y_pred)

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy', mean_pred])

## 训练

### 训练模型一般使用fit函数

In [14]:
# For a single-input model with 2 classes (binary classification):

model = Sequential()
model.add(Dense(32, activation='relu', input_dim=100))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [15]:
# 产生 dummy 数据
import numpy as np
data = np.random.random((1000, 100))
labels = np.random.randint(2, size=(1000, 1))

In [17]:
data[:1]

array([[ 0.97000729,  0.27880024,  0.72808653,  0.55075555,  0.06170551,
         0.82938643,  0.01874319,  0.24535527,  0.05332449,  0.86141981,
         0.29102786,  0.45487401,  0.13347569,  0.77468637,  0.56919523,
         0.39325105,  0.98142375,  0.50374533,  0.13577048,  0.05122722,
         0.6420219 ,  0.27390487,  0.80650736,  0.64882963,  0.95493556,
         0.29044035,  0.74793219,  0.967385  ,  0.05849997,  0.4984678 ,
         0.77520196,  0.31331559,  0.87324149,  0.83396069,  0.94450822,
         0.95601746,  0.10373711,  0.62673184,  0.17531107,  0.66179605,
         0.83323057,  0.91678036,  0.92417592,  0.5474703 ,  0.86658151,
         0.45611861,  0.54345194,  0.29440197,  0.96114044,  0.48247699,
         0.95947698,  0.41088678,  0.03258962,  0.75552755,  0.12640064,
         0.89304284,  0.98162835,  0.25784015,  0.43572026,  0.23969605,
         0.63984622,  0.50432791,  0.02708993,  0.31563938,  0.34639455,
         0.20151555,  0.58490369,  0.41494418,  0.7

In [20]:
labels[:5]

array([[1],
       [0],
       [1],
       [0],
       [1]])

In [21]:
# Train the model, iterating on the data in batches of 32 samples
model.fit(data, labels, epochs=10, batch_size=32)

Epoch 1/10
1000/1000 [==============================] - 0s - loss: 0.7249 - acc: 0.5020     
Epoch 2/10
1000/1000 [==============================] - 0s - loss: 0.7009 - acc: 0.5330     
Epoch 3/10
1000/1000 [==============================] - 0s - loss: 0.6953 - acc: 0.5360     
Epoch 4/10
1000/1000 [==============================] - 0s - loss: 0.6887 - acc: 0.5580     
Epoch 5/10
1000/1000 [==============================] - 0s - loss: 0.6836 - acc: 0.5560     
Epoch 6/10
1000/1000 [==============================] - 0s - loss: 0.6766 - acc: 0.5660     
Epoch 7/10
1000/1000 [==============================] - 0s - loss: 0.6740 - acc: 0.5800     
Epoch 8/10
1000/1000 [==============================] - 0s - loss: 0.6675 - acc: 0.5950     
Epoch 9/10
1000/1000 [==============================] - 0s - loss: 0.6622 - acc: 0.5980     
Epoch 10/10
1000/1000 [==============================] - 0s - loss: 0.6579 - acc: 0.6090     


另一个例子

In [22]:
# For a single-input model with 10 classes (categorical classification):

model = Sequential()
model.add(Dense(32, activation='relu', input_dim=100))
model.add(Dense(10, activation='softmax'))
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [23]:
# Generate dummy data
import numpy as np
data = np.random.random((1000, 100))
labels = np.random.randint(10, size=(1000, 1))

In [25]:
import keras
# Convert labels to categorical one-hot encoding
one_hot_labels = keras.utils.to_categorical(labels, num_classes=10)

In [26]:
# Train the model, iterating on the data in batches of 32 samples
model.fit(data, one_hot_labels, epochs=10, batch_size=32)

Epoch 1/10
1000/1000 [==============================] - 0s - loss: 2.3599 - acc: 0.1100     
Epoch 2/10
1000/1000 [==============================] - 0s - loss: 2.3087 - acc: 0.1210     
Epoch 3/10
1000/1000 [==============================] - 0s - loss: 2.2952 - acc: 0.1360     
Epoch 4/10
1000/1000 [==============================] - 0s - loss: 2.2836 - acc: 0.1480     
Epoch 5/10
1000/1000 [==============================] - 0s - loss: 2.2745 - acc: 0.1550     
Epoch 6/10
1000/1000 [==============================] - 0s - loss: 2.2641 - acc: 0.1600     
Epoch 7/10
1000/1000 [==============================] - 0s - loss: 2.2539 - acc: 0.1810     
Epoch 8/10
1000/1000 [==============================] - 0s - loss: 2.2457 - acc: 0.1750     
Epoch 9/10
1000/1000 [==============================] - 0s - loss: 2.2343 - acc: 0.1800     
Epoch 10/10
1000/1000 [==============================] - 0s - loss: 2.2231 - acc: 0.2010     


## 例子

In [27]:
labels

array([[4],
       [5],
       [1],
       [2],
       [2],
       [4],
       [7],
       [1],
       [1],
       [5],
       [5],
       [6],
       [1],
       [9],
       [8],
       [3],
       [9],
       [5],
       [7],
       [1],
       [0],
       [4],
       [6],
       [7],
       [9],
       [4],
       [5],
       [1],
       [0],
       [7],
       [5],
       [4],
       [5],
       [1],
       [6],
       [4],
       [9],
       [1],
       [3],
       [6],
       [9],
       [8],
       [7],
       [8],
       [0],
       [5],
       [6],
       [8],
       [7],
       [3],
       [0],
       [5],
       [7],
       [9],
       [9],
       [7],
       [0],
       [4],
       [4],
       [6],
       [2],
       [9],
       [5],
       [1],
       [7],
       [8],
       [0],
       [8],
       [3],
       [1],
       [6],
       [9],
       [1],
       [9],
       [1],
       [5],
       [1],
       [7],
       [3],
       [0],
       [5],
       [4],
       [7],
    

In [30]:
one_hot_labels[:5]

array([[ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])