# 例子3 建造神经网络

### 建造一个完整的神经网络,  包括  添加神经层  ,  计算误差  ,  训练步骤  ,  判断是否在学习.

In [1]:
import tensorflow as tf
import numpy as np

## 神经层函数（详见上一课）

In [2]:
def add_layer(inputs, in_size, out_size, activation_function=None):
    Weights = tf.Variable(tf.random_normal([in_size, out_size]))
    biases = tf.Variable(tf.zeros([1, out_size]) + 0.1)
    Wx_plus_b = tf.matmul(inputs, Weights) + biases
    if activation_function is None:
        outputs = Wx_plus_b
    else:
        outputs = activation_function(Wx_plus_b)
    return outputs

## 导入数据

这里的x_data和y_data并不是严格的一元二次函数的关系，

因为我们多加了一个noise

In [3]:
x_data = np.linspace(-1,1,300, dtype=np.float32)[:, np.newaxis]

In [13]:
x_data[:5]

array([[-1.        ],
       [-0.99331105],
       [-0.9866221 ],
       [-0.97993308],
       [-0.97324413]], dtype=float32)

In [6]:
print(np.newaxis)

None


In [7]:
noise = np.random.normal(0, 0.05, x_data.shape).astype(np.float32)

In [12]:
noise[:5]

array([[-0.02137901],
       [-0.07042874],
       [-0.09630427],
       [ 0.01611654],
       [ 0.00932103]], dtype=float32)

In [9]:
x_data.shape

(300, 1)

In [11]:
np.random.normal(0, 1, 10)

array([ 0.10138769,  1.95213316, -0.76161914, -0.21433615, -1.36350175,
       -0.92862147,  0.19847386,  0.75361085,  2.19596828,  1.81423788])

In [14]:
np.linspace(-1,1,10, dtype=np.float32)

array([-1.        , -0.77777779, -0.55555558, -0.33333334, -0.11111111,
        0.11111111,  0.33333334,  0.55555558,  0.77777779,  1.        ], dtype=float32)

In [15]:
np.linspace(-1,1,10, dtype=np.float32)[:, np.newaxis]

array([[-1.        ],
       [-0.77777779],
       [-0.55555558],
       [-0.33333334],
       [-0.11111111],
       [ 0.11111111],
       [ 0.33333334],
       [ 0.55555558],
       [ 0.77777779],
       [ 1.        ]], dtype=float32)

In [16]:
np.linspace(-1,1,10, dtype=np.float32)[:]

array([-1.        , -0.77777779, -0.55555558, -0.33333334, -0.11111111,
        0.11111111,  0.33333334,  0.55555558,  0.77777779,  1.        ], dtype=float32)

In [18]:
np.linspace(-1,1,10, dtype=np.float32)[:,]

array([-1.        , -0.77777779, -0.55555558, -0.33333334, -0.11111111,
        0.11111111,  0.33333334,  0.55555558,  0.77777779,  1.        ], dtype=float32)

In [19]:
np.linspace(-1,1,10, dtype=np.float32)[:, None]

array([[-1.        ],
       [-0.77777779],
       [-0.55555558],
       [-0.33333334],
       [-0.11111111],
       [ 0.11111111],
       [ 0.33333334],
       [ 0.55555558],
       [ 0.77777779],
       [ 1.        ]], dtype=float32)

In [20]:
y_data = np.square(x_data) - 0.5 + noise

In [22]:
y_data[:5]

array([[ 0.47862101],
       [ 0.41623813],
       [ 0.37711892],
       [ 0.47638538],
       [ 0.45652515]], dtype=float32)

利用占位符定义我们所需的神经网络的输入。 tf.placeholder()就是代表占位符，

这里的None代表无论输入有多少都可以，

因为输入只有一个特征，所以这里是1


In [23]:
xs = tf.placeholder(tf.float32, [None, 1])
ys = tf.placeholder(tf.float32, [None, 1])

## 定义神经层

通常神经层都包括输入层、隐藏层和输出层。

In [24]:
l1 = add_layer(xs, 1, 10, activation_function=tf.nn.relu)

这里使用 Tensorflow 自带的激励函数tf.nn.relu。

## 定义输出层

In [25]:
prediction = add_layer(l1, 10, 1, activation_function=None)

计算预测值prediction和真实值的误差，对二者

### 差的平方求和再取平均

In [26]:
loss = tf.reduce_mean(tf.reduce_sum(tf.square(ys - prediction),
                     reduction_indices=[1]))

tf.train.GradientDescentOptimizer()中的值通常都小于1，这里取的是0.1，代表以0.1的效率来最小化误差loss。

In [27]:
train_step = tf.train.GradientDescentOptimizer(0.1).minimize(loss)

In [28]:
init = tf.global_variables_initializer()

### 定义Session，并用 Session 来执行 init 初始化步骤。

In [29]:
sess = tf.Session()
sess.run(init)

## 训练

In [31]:
for i in range(1000):
    # training
    sess.run(train_step, feed_dict={xs: x_data, ys: y_data})
    if i % 50 == 0:
        print(sess.run(loss, feed_dict={xs: x_data, ys: y_data}))

0.00444646
0.00428488
0.00413104
0.00398703
0.00386003
0.00374639
0.00364132
0.0035391
0.00344918
0.00336462
0.00327998
0.00320029
0.00312092
0.003051
0.00298631
0.00292383
0.00286659
0.00281373
0.00276728
0.00272648
