In [1]:
# coding:utf-8
import numpy as np

In [2]:
def relu(z):
    return np.maximum(z, 0.0)

In [31]:
def percepT(x, y, iter):  # 感知机原始形式
    n = np.shape(x)[1]
    m = len(x)
    theta = np.ones(n)
    alpha = 0.02
    for it in range(iter):
        l = 0
#         print(it)
        for k in range(m):
            a=relu(x[k].dot(theta.T))
            if (a) * y[k] < 0:
                l = 1
                theta+=alpha *(y[k]-a)*x[k]
        if l == 0:
            break
    return theta

In [4]:
N=3
a=range(2**N)
a

range(0, 8)

In [5]:
x=[bin(i)[2:].zfill(N) for i in a]
x

['000', '001', '010', '011', '100', '101', '110', '111']

In [8]:
[i for i in a]

[0, 1, 2, 3, 4, 5, 6, 7]

In [9]:
[bin(i) for i in a]

['0b0', '0b1', '0b10', '0b11', '0b100', '0b101', '0b110', '0b111']

In [10]:
[bin(i)[2:] for i in a]

['0', '1', '10', '11', '100', '101', '110', '111']

In [11]:
[bin(i)[2:].zfill(N) for i in a]

['000', '001', '010', '011', '100', '101', '110', '111']

In [12]:
[bin(i)[2:].zfill(N) for i in range(10)]

['000', '001', '010', '011', '100', '101', '110', '111', '1000', '1001']

In [13]:
data=np.array([[int(i) for i in j ]for j in x])
data

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1]])

In [22]:
y=np.array([i[0]*i[2] for i in data])
y

array([0, 0, 0, 0, 0, 1, 0, 1])

In [24]:
y[y==0]=-1
y

array([-1, -1, -1, -1, -1,  1, -1,  1])

In [32]:
theta = percepT(data, np.array(y), 100)
theta

array([-0.01272316, -0.1729134 , -0.01583692])

In [33]:
print(theta)  # [-0.01272316 -0.1729134  -0.01583692]

[-0.01272316 -0.1729134  -0.01583692]


In [34]:
for i,j in zip(data,np.array(y)):
    print(relu(i.dot(theta.T))* j>=0)

True
True
True
True
True
True
True
True
