In [1]:
import tensorflow as tf
import numpy as np

In [17]:
# 使用 NumPy 生成假数据(phony data), 总共 100 个点.
x_data = np.float32(np.random.rand(2, 100)) # 随机输入
y_data = np.dot([0.100, 0.200], x_data) + 0.300

In [22]:
y_data

array([ 0.34432232,  0.44877555,  0.47708763,  0.51339244,  0.42723691,
        0.51715146,  0.4143393 ,  0.34248789,  0.43255919,  0.31451497,
        0.40962519,  0.47049194,  0.36860847,  0.37366657,  0.36238338,
        0.46502073,  0.50545993,  0.50239601,  0.51345224,  0.36872168,
        0.53527834,  0.40736134,  0.44668893,  0.46583491,  0.56957983,
        0.43551306,  0.47180258,  0.40259519,  0.32935526,  0.56773856,
        0.57826352,  0.37419455,  0.46390646,  0.55879653,  0.3069811 ,
        0.44533665,  0.40129313,  0.40032951,  0.39495025,  0.50232083,
        0.43709962,  0.54674144,  0.45391039,  0.46856998,  0.43164828,
        0.50348805,  0.42959178,  0.47693043,  0.34603533,  0.52759204,
        0.43372721,  0.43505528,  0.44810789,  0.46234645,  0.30875964,
        0.4202391 ,  0.55922403,  0.34888061,  0.56585639,  0.43347057,
        0.53679817,  0.48884403,  0.50367533,  0.48549662,  0.52100833,
        0.43391259,  0.35993765,  0.45280465,  0.51049632,  0.48

In [23]:
# 构造一个线性模型
# 
b = tf.Variable(tf.zeros([1]))
W = tf.Variable(tf.random_uniform([1, 2], -1.0, 1.0))
y = tf.matmul(W, x_data) + b

In [24]:
b

<tf.Variable 'Variable:0' shape=(1,) dtype=float32_ref>

In [25]:
# 最小化方差
loss = tf.reduce_mean(tf.square(y - y_data))
optimizer = tf.train.GradientDescentOptimizer(0.5)
train = optimizer.minimize(loss)

In [26]:
# 初始化变量
init = tf.initialize_all_variables()

Instructions for updating:
Use `tf.global_variables_initializer` instead.


In [27]:
# 启动图 (graph)
sess = tf.Session()
sess.run(init)

In [28]:
sess.run(b)

array([ 0.], dtype=float32)

In [29]:
sess.run(W)

array([[-0.50738502, -0.3036139 ]], dtype=float32)

In [30]:
sess.run(y)

array([[-0.17825711, -0.46710438, -0.30691212, -0.58911228, -0.43083605,
        -0.39702052, -0.25587761, -0.13390058, -0.421404  , -0.06422111,
        -0.20093158, -0.32167837, -0.25640047, -0.14665282, -0.22286344,
        -0.36522818, -0.59231639, -0.65073109, -0.58877701, -0.33353761,
        -0.66705942, -0.42495102, -0.54230082, -0.43883374, -0.72213656,
        -0.27334219, -0.29238883, -0.41867739, -0.10027099, -0.66730636,
        -0.75882292, -0.17213541, -0.56192929, -0.64316577, -0.02405809,
        -0.28313887, -0.46740472, -0.31009898, -0.42184991, -0.34772807,
        -0.44308084, -0.65680999, -0.47004944, -0.34542423, -0.28570446,
        -0.49724317, -0.29796028, -0.33032882, -0.23269264, -0.68800789,
        -0.25293112, -0.51341289, -0.42413414, -0.46628821, -0.01770614,
        -0.41713122, -0.68865311, -0.13807769, -0.70389092, -0.43572247,
        -0.6887604 , -0.29599112, -0.64239872, -0.63497889, -0.64325052,
        -0.32811213, -0.2383676 , -0.33131847, -0.4

In [33]:
# 拟合平面
for step in range(0, 201):
    sess.run(train)
    if step % 20 == 0:
        print(step, sess.run(W), sess.run(b))

0 [[-0.02861232  0.11788073]] [ 0.83311242]
20 [[ 0.03286885  0.13240035]] [ 0.36865696]
40 [[ 0.08324765  0.17983271]] [ 0.31871915]
60 [[ 0.09569434  0.19414073]] [ 0.3051362]
80 [[ 0.0988677   0.19832465]] [ 0.30141538]
100 [[ 0.09969713  0.19952571]] [ 0.3003912]
120 [[ 0.099918    0.19986658]] [ 0.30010831]
140 [[ 0.09997761  0.19996263]] [ 0.30003002]
160 [[ 0.09999384  0.19998954]] [ 0.30000836]
180 [[ 0.0999983   0.19999707]] [ 0.30000231]
200 [[ 0.09999952  0.19999917]] [ 0.30000067]
